#ifndef QUICKTCP_DPDK_WRAPPER_H
#define QUICKTCP_DPDK_WRAPPER_H

#include <rte_eal.h>
#include <rte_lcore.h>
#include <rte_launch.h>
#include <rte_per_lcore.h>
#include <rte_cycles.h>
#include <rte_atomic.h>
#include <rte_branch_prediction.h>
#include <rte_byteorder.h>
#include <rte_common.h>
#include <rte_config.h>
#include <rte_debug.h>
#include <rte_errno.h>
#include <rte_log.h>
#include <rte_malloc.h>
#include <rte_memcpy.h>
#include <rte_memory.h>
#include <rte_mempool.h>
#include <rte_mbuf.h>
#include <rte_ring.h>
#include <rte_ethdev.h>
#include <rte_ether.h>
#include <rte_arp.h>
#include <rte_ip.h>
#include <rte_tcp.h>
#include <rte_udp.h>
#include <rte_icmp.h>
#include <rte_hash.h>
#include <rte_hash_crc.h>
#include <rte_jhash.h>
#include <rte_spinlock.h>
#include <rte_rwlock.h>
#include <rte_prefetch.h>
#include <rte_random.h>
#include <rte_timer.h>
#include <rte_version.h>

#endif
